config/routes.rb
Rails.application.routes.draw do
  resources :vehicles  
  root 'vehicles#index' 
  mount Vehicles::VehiclesAPI => '/api/vehicles'  


  # get 'vehicles/index'
  # get 'vehicles/show'
  # get 'vehicles/new'
  # get 'vehicles/create'
  # get 'vehicles/edit'
  # get 'vehicles/update'
  # get 'vehicles/destroy'
  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    validates :name, presence: true   
validates :price, presence: true, numericality: {:greater_than => 0}   
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

    # GET method to get a product by id   
    def show   
      @vehicle = Vehicle.find(params[:id])   
    end  

   # GET method for the new product form   
   def new   
    @vehicle = Vehicle.new   
  end   

   # POST method for processing form data   
   def create   
    @vehicle = Vehicle.new(vehicle_params)   
    if @vehicle.save   
      flash[:notice] = 'Vehicle added!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to edit vehicle!'   
      render :new   
    end   
  end   

  # GET method for editing a product based on id   
  def edit   
    @vehicle = Vehicle.find(params[:id])   
  end   

  # PUT method for updating in database a product based on id   
  def update   
    @vehicle = Vehicle.find(params[:id])   
    if @vehicle.update_attributes(vehicle_params)   
      flash[:notice] = 'Vehicle updated!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to edit vehicle!'   
      render :edit   
    end   
  end   


  # DELETE method for deleting a vehicle from database based on id   
  def destroy   
    @vehicle = Vehicle.find(params[:id])   
    if @vehicle.delete   
      flash[:notice] = 'Vehicle deleted!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to delete this Vehicle!'   
      render :destroy   
    end   
  end   


    # we used strong parameters for the validation of params   
    def vehicle_params   
      params.require(:vehicle).permit(:name, :price, :picture)   
    end   





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/application/vehicles.html.erb
<h2>Vehicle View</h2>   
<table border="2">   
      <thead>   
      <tr>   
        <th>Name</th>   
        <th>Price</th>   
        <th>picture</th>   
        <th>created</th>   
          <th>updated</th>   
      </tr>   
      </thead>   
      <tbody>   
      <% @vehicles.each do |vehicle| %>   
          <tr>   
            <td><%= vehicle.name %></td>   
            <td><%= vehicle.price %></td>   
          
            <td><%= vehicle.picture %></td>   
            <td><%= vehicle.created_at %></td>   
            <td><%= vehicle.updated_at %></td>   

                
            </td>   
          </tr>   
      <% end %>   
      </tbody>   
    </table>   

app/views/hello/index.html.erb
<h2>Hello World</h2>   
<p>   
  Today is 1st Dcember , Wednesday.   
</p>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newappp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

<%= stylesheet_link_tag  'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' %>  
 
 <style>
    .mycar{
      width:130px;
      height:90px
    }
    .mycarShow{
      width:500px;
      height:240px
    }
  </style>
  </head>

  <body>
 <div class="container">  
<div><% if flash[:notice] %>  
<div><%= flash[:notice] %></div>  
<% end %> <%= yield %></div>  
</div>  
</div>  




    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' %>  
   </body>
</html>

app/views/vehicles/create.html.erb
<h1>Vehicles#create</h1>
<p>Find me in app/views/vehicles/create.html.erb</p>

app/views/vehicles/destroy.html.erb
<h1>Vehicles#destroy</h1>
<p>Find me in app/views/vehicles/destroy.html.erb</p>

app/views/vehicles/edit.html.erb
<h1>Vehicles#edit</h1>
<div class="container">   
  
<%= form_for @vehicle, url: {action: :update} do |f| %>   
     
   <h3>Add a Vehicle</h3>   
 <%= "<div>#{@vehicle.errors.full_messages.first}</div>".html_safe if @vehicle.errors.any? %>   
    <p>   
  
     <div>   
            <label>Vehicle Name</label>   
            <%= f.text_field :name %>   
     </div>   
  
     <div>   
            <label>Price</label>   
            <%= f.text_field :price %>   
     </div>   
        
     <div>   
            <label>Image URL</label>   
            <%= f.text_field :picture %>   
     </div>   
  
      </p>   
   <div>   
      <%= link_to 'Back', { controller: 'vehicles', action: 'index'} %>   
      <%= f.submit 'Update Vehicle' %>   
    </div>   
<% end %>   
t;/div>  

app/views/vehicles/index.html.erb
<h1>Vehicles#index</h1>
<p>Find me in app/views/vehicles/index.html.erb</p>
   <div>   
        <%= link_to 'Add Vehicle', new_vehicle_path %>   
      </div>   

<table class="table table-dark">   
      <thead>   
      <tr>   
        <th scope="col">Name</th>   
        <th scope="col">Price</th>   
        <th scope="col">picture</th>   
        <th scope="col">created</th>   
          <th scope="col">updated</th>   
             <th scope="col">Actions</th>   
      </tr>   
      </thead>   
      <tbody>   
      <% @vehicles.each do |vehicle| %>   
          <tr>   
            <td><%= vehicle.name %></td>   
            <td><%= vehicle.price %></td>   
          
            <td><img class="mycar" src=<%=vehicle.picture%> /></td>   
            <td><%= vehicle.created_at %></td>   
            <td><%= vehicle.updated_at %></td>   
     <td>   
               <div>   
                <%= link_to 'Show', vehicle_path(vehicle) %>   
                <%= link_to 'Edit', edit_vehicle_path(vehicle) %>   
                <%= link_to 'Delete',vehicle_path(vehicle), method: :delete %>   
              </div>   
            </td>   

          </tr>   
      <% end %>   
      </tbody>   
    </table>   

app/views/vehicles/new.html.erb
<h1>Vehicles#new</h1>
 <div class="container">   
  <%= form_for @vehicle, url: {action: :create} do |f| %>   
      <div>   
        <h3>Add a Vehicle</h3>   
      </div>   
      <div>   
        <p>   
          <%= "<div>#{@vehicle.errors.full_messages.first}</div>".html_safe if @vehicle.errors.any? %>   
        <div>   
            <label>Vehicle Name</label>   
              <%= f.text_field :name %>   
        </div>   
  
        <div>   
             <label>Price</label>   
             <%= f.text_field :price %>   
        </div>   
  
        <div>   
           <label>Image URL</label>   
              <%= f.text_field :picture %>   
        </div>   
         </p>   
      </div>   
      <div>   
        <%= link_to 'Back', { controller: 'vehicles', action: 'index'} %>   
        <%= f.submit 'Create Vehicle' %>   
      </div>   
  <% end %>   
</div>  

app/views/vehicles/show.html.erb
<h1>Vehicles#show</h1>
 <div class="container">        
        
       
            <div>   
              <label>Vehicle Name</label>   
              <%= @vehicle.name %>   
            </div>   
  
            <div>   
              <label>Price</label>   
              <h4><%= @vehicle.price %>  </h4> 
            </div>   
            
            <div>   
              <label>Picture</label>   
              <img class="mycarShow" src=<%= @vehicle.picture %> />  
            </div>   
         
      <div>   
        <%= link_to 'Back', { controller: 'vehicles', action: 'index'} %>   
      </div>   
</div>  

app/views/vehicles/update.html.erb
<h1>Vehicles#update</h1>
<p>Find me in app/views/vehicles/update.html.erb</p>

app/views/vehicles/vehicles.html.erb
<h1>Vehicles html file </h1>